"""50 Filipino celebrities — bio data for the needle-in-a-haystack test.

Each top-level key is one person, scanned as its own enclosure by laya.
Test data — facts are approximate, don't treat as authoritative.
"""

DATA = {
    "jose_rizal": {
        "full_name": "José Protasio Rizal Mercado y Alonso Realonda",
        "birthdate": "June 19, 1861",
        "birthplace": "Calamba, Laguna, Philippines",
        "nationality": "Filipino",
        "occupation": "ophthalmologist, novelist, poet",
        "known_for": "National hero of the Philippines; writings inspired the revolution",
        "parents": {"father": "Francisco Mercado", "mother": "Teodora Alonso"},
        "relationships": {"spouse": "Josephine Bracken", "notable": "Leonor Rivera, his first love"},
    },
    "manny_pacquiao": {
        "full_name": "Manny Pacquiao",
        "birthdate": "December 17, 1978",
        "birthplace": "Kibawe, Bukidnon, Philippines",
        "nationality": "Filipino",
        "occupation": "professional boxer, politician",
        "known_for": "Only eight-division world champion in boxing history; former senator",
        "parents": {"father": "Rosalio Pacquiao", "mother": "Dionisia Dapidran"},
        "relationships": {"spouse": "Jinkee Pacquiao", "children": "Jimuel, Michael, Mary Divine Grace, Queenie, Israel"},
    },
    "lea_salonga": {
        "full_name": "Lea Salonga",
        "birthdate": "February 22, 1971",
        "birthplace": "Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "singer, actress",
        "known_for": "Miss Saigon; singing voice of Disney's Jasmine and Mulan",
        "parents": {"father": "Feliciano Salonga", "mother": "Ligaya Imutan"},
        "relationships": {"spouse": "Robert Chien", "children": "Nicole Chien"},
    },
    "kathryn_bernardo": {
        "full_name": "Kathryn Bernardo",
        "birthdate": "March 26, 1996",
        "birthplace": "Cabanatuan, Nueva Ecija, Philippines",
        "nationality": "Filipino",
        "occupation": "actress",
        "known_for": "Hello, Love, Goodbye — one of the highest-grossing Filipino films",
        "parents": {"father": "Teodore Bernardo", "mother": "Luzviminda Bernardo"},
        "relationships": {"former_partner": "Daniel Padilla (2012–2023)"},
    },
    "alden_richards": {
        "full_name": "Alden Richards",
        "birthdate": "January 2, 1992",
        "birthplace": "Santa Rosa, Laguna, Philippines",
        "nationality": "Filipino",
        "occupation": "actor, singer",
        "known_for": "AlDub love team and the Kalyeserye segment of Eat Bulaga",
        "parents": {"father": "Richard Faulkerson", "mother": "Rosario Reyes"},
        "relationships": {"status": "single"},
    },
    "nadine_lustre": {
        "full_name": "Nadine Lustre",
        "birthdate": "October 31, 1993",
        "birthplace": "Quezon City, Philippines",
        "nationality": "Filipino",
        "occupation": "actress, singer",
        "known_for": "Never Not Love You; former member of Pop Girls",
        "parents": {"father": "Ulysses Lustre", "mother": "Myraquel Lustre"},
        "relationships": {"partner": "Christophe Bariou", "former_partner": "James Reid"},
    },
    "sarah_geronimo": {
        "full_name": "Sarah Geronimo",
        "birthdate": "July 25, 1988",
        "birthplace": "Santa Cruz, Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "singer, actress",
        "known_for": "Popstar Royalty; winner of Star for a Night",
        "parents": {"father": "Delfin Geronimo", "mother": "Divina Templo"},
        "relationships": {"spouse": "Matteo Guidicelli"},
    },
    "coco_martin": {
        "full_name": "Coco Martin",
        "birthdate": "November 1, 1981",
        "birthplace": "Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "actor, director",
        "known_for": "FPJ's Ang Probinsyano — longest-running Philippine action drama",
        "parents": {"father": "Ramon Nacianceno", "mother": "Maria Teresa Cacho"},
        "relationships": {"partner": "Julia Montes"},
    },
    "anne_curtis": {
        "full_name": "Anne Curtis",
        "birthdate": "February 17, 1985",
        "birthplace": "Yarrawonga, Victoria, Australia",
        "nationality": "Filipino-Australian",
        "occupation": "actress, TV host",
        "known_for": "It's Showtime host; lead role in BuyBust",
        "parents": {"father": "James Curtis-Smith", "mother": "Carmencita Ojales"},
        "relationships": {"spouse": "Erwan Heussaff", "children": "Dahlia Amélie"},
    },
    "vice_ganda": {
        "full_name": "Vice Ganda",
        "birthdate": "March 31, 1976",
        "birthplace": "Tondo, Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "comedian, TV host",
        "known_for": "It's Showtime mainstay; highest-grossing Filipino comedy films",
        "parents": {"father": "Reynaldo Viceral", "mother": "Rosario Viceral"},
        "relationships": {"partner": "Ion Perez"},
    },
    "erwan_heussaff": {
        "full_name": "Erwan Heussaff",
        "birthdate": "January 29, 1987",
        "birthplace": "Makati, Philippines",
        "nationality": "Filipino-French",
        "occupation": "content creator, chef, restaurateur",
        "known_for": "The Fat Kid Inside food and travel channel",
        "parents": {"father": "Paul Heussaff", "mother": "Cynthia Adea"},
        "relationships": {"spouse": "Anne Curtis", "children": "Dahlia Amélie"},
    },
    "daniel_padilla": {
        "full_name": "Daniel Padilla",
        "birthdate": "April 26, 1995",
        "birthplace": "Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "actor, singer",
        "known_for": "Teen King; KathNiel love team with Kathryn Bernardo",
        "parents": {"father": "Rommel Padilla", "mother": "Karla Estrada"},
        "relationships": {"former_partner": "Kathryn Bernardo (2012–2023)"},
    },
    "liza_soberano": {
        "full_name": "Liza Soberano",
        "birthdate": "January 4, 1998",
        "birthplace": "Santa Clara, California, USA",
        "nationality": "Filipino-American",
        "occupation": "actress",
        "known_for": "Alone/Together; Hollywood debut in Lisa Frankenstein",
        "parents": {"father": "John Soberano", "mother": "Jacqulyn Han"},
        "relationships": {"partner": "Enrique Gil"},
    },
    "enrique_gil": {
        "full_name": "Enrique Gil",
        "birthdate": "March 30, 1992",
        "birthplace": "Cebu City, Philippines",
        "nationality": "Filipino",
        "occupation": "actor, dancer",
        "known_for": "Forevermore; LizQuen love team with Liza Soberano",
        "parents": {"father": "Enrique Gil Sr.", "mother": "Bambi Gil"},
        "relationships": {"partner": "Liza Soberano"},
    },
    "james_reid": {
        "full_name": "James Reid",
        "birthdate": "May 11, 1993",
        "birthplace": "Sydney, Australia",
        "nationality": "Filipino-Australian",
        "occupation": "singer, actor",
        "known_for": "JaDine love team; founder of Careless Music label",
        "parents": {"father": "Malcolm Reid", "mother": "Maria Aprilyn Marquinez"},
        "relationships": {"partner": "Issa Pressman", "former_partner": "Nadine Lustre"},
    },
    "maine_mendoza": {
        "full_name": "Maine Mendoza",
        "birthdate": "March 3, 1995",
        "birthplace": "Santa Maria, Bulacan, Philippines",
        "nationality": "Filipino",
        "occupation": "actress, TV host",
        "known_for": "Yaya Dub of the AlDub phenomenon on Eat Bulaga",
        "parents": {"father": "Teodoro Mendoza", "mother": "Mary Ann Mendoza"},
        "relationships": {"spouse": "Arjo Atayde"},
    },
    "marian_rivera": {
        "full_name": "Marian Rivera",
        "birthdate": "August 12, 1984",
        "birthplace": "Madrid, Spain",
        "nationality": "Filipino-Spanish",
        "occupation": "actress, dancer",
        "known_for": "Marimar and Dyesebel title roles",
        "parents": {"father": "Francisco Gracia", "mother": "Amalia Rivera"},
        "relationships": {"spouse": "Dingdong Dantes", "children": "Zia, Sixto"},
    },
    "dingdong_dantes": {
        "full_name": "Dingdong Dantes",
        "birthdate": "August 2, 1980",
        "birthplace": "Quezon City, Philippines",
        "nationality": "Filipino",
        "occupation": "actor, TV host",
        "known_for": "Marimar, Alyas Robin Hood; Family Feud Philippines host",
        "parents": {"father": "Jose Dantes", "mother": "Angeline Gonzalez"},
        "relationships": {"spouse": "Marian Rivera", "children": "Zia, Sixto"},
    },
    "bea_alonzo": {
        "full_name": "Bea Alonzo",
        "birthdate": "October 17, 1987",
        "birthplace": "Cainta, Rizal, Philippines",
        "nationality": "Filipino",
        "occupation": "actress",
        "known_for": "One More Chance; Start-Up PH lead",
        "parents": {"father": "Philip Ranollo", "mother": "Mary Anne Ranollo"},
        "relationships": {"former_partner": "Dominic Roque"},
    },
    "angel_locsin": {
        "full_name": "Angel Locsin",
        "birthdate": "April 23, 1985",
        "birthplace": "Santa Maria, Bulacan, Philippines",
        "nationality": "Filipino",
        "occupation": "actress, philanthropist",
        "known_for": "Darna and Mulawin; humanitarian work with the Red Cross",
        "parents": {"father": "Angelo Colmenares", "mother": "Emma Blay"},
        "relationships": {"spouse": "Neil Arce"},
    },
    "john_lloyd_cruz": {
        "full_name": "John Lloyd Cruz",
        "birthdate": "June 24, 1983",
        "birthplace": "Pasig City, Philippines",
        "nationality": "Filipino",
        "occupation": "actor",
        "known_for": "One More Chance, Four Sisters and a Wedding",
        "parents": {"father": "Atilano Cruz", "mother": "Aida Espidol"},
        "relationships": {"former_partner": "Ellen Adarna", "children": "Elias Modesto"},
    },
    "jericho_rosales": {
        "full_name": "Jericho Rosales",
        "birthdate": "September 22, 1979",
        "birthplace": "Quezon City, Philippines",
        "nationality": "Filipino",
        "occupation": "actor",
        "known_for": "Pangako Sa 'Yo; international film roles",
        "parents": {"father": "Santiago Rosales", "mother": "Rosario Vibar"},
        "relationships": {"former_spouse": "Kim Jones"},
    },
    "piolo_pascual": {
        "full_name": "Piolo Pascual",
        "birthdate": "January 12, 1977",
        "birthplace": "Malate, Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "actor, singer",
        "known_for": "Dekada '70; Don't Give Up on Us",
        "parents": {"father": "Philip Pascual", "mother": "Amelia Nonato"},
        "relationships": {"children": "Iñigo Pascual"},
    },
    "kim_chiu": {
        "full_name": "Kim Chiu",
        "birthdate": "April 19, 1990",
        "birthplace": "Tacloban, Leyte, Philippines",
        "nationality": "Filipino",
        "occupation": "actress, TV host",
        "known_for": "Pinoy Big Brother winner; It's Showtime host; Linlang",
        "parents": {"father": "William Chiu", "mother": "Louella Yap"},
        "relationships": {"former_partner": "Xian Lim"},
    },
    "xian_lim": {
        "full_name": "Xian Lim",
        "birthdate": "July 12, 1989",
        "birthplace": "San Francisco, California, USA",
        "nationality": "Filipino-American",
        "occupation": "actor, filmmaker",
        "known_for": "My Binondo Girl; KimXi love team",
        "parents": {"father": "Godofredo Lim", "mother": "Mary Anne Lim"},
        "relationships": {"partner": "Iris Lee", "former_partner": "Kim Chiu"},
    },
    "gerald_anderson": {
        "full_name": "Gerald Anderson",
        "birthdate": "March 7, 1989",
        "birthplace": "Subic Bay, Zambales, Philippines",
        "nationality": "Filipino-American",
        "occupation": "actor",
        "known_for": "Budoy; A Soldier's Heart",
        "parents": {"father": "Gerald Anderson Sr.", "mother": "Evangeline Opsima"},
        "relationships": {"partner": "Julia Barretto"},
    },
    "julia_barretto": {
        "full_name": "Julia Barretto",
        "birthdate": "March 10, 1997",
        "birthplace": "Marikina, Philippines",
        "nationality": "Filipino",
        "occupation": "actress",
        "known_for": "Vince and Kath and James; Barretto showbiz family",
        "parents": {"father": "Dennis Padilla", "mother": "Marjorie Barretto"},
        "relationships": {"partner": "Gerald Anderson", "former_partner": "Joshua Garcia"},
    },
    "joshua_garcia": {
        "full_name": "Joshua Garcia",
        "birthdate": "October 7, 1997",
        "birthplace": "Bauan, Batangas, Philippines",
        "nationality": "Filipino",
        "occupation": "actor, dancer",
        "known_for": "The Good Son; Unbreak My Heart",
        "parents": {"father": "Geo Garcia", "mother": "Marife Espineli"},
        "relationships": {"former_partner": "Julia Barretto"},
    },
    "andrea_brillantes": {
        "full_name": "Andrea Brillantes",
        "birthdate": "March 12, 2003",
        "birthplace": "Taytay, Rizal, Philippines",
        "nationality": "Filipino",
        "occupation": "actress",
        "known_for": "Kadenang Ginto; Senior High",
        "parents": {"father": "Byron Gorostiza", "mother": "Belle Gorostiza"},
        "relationships": {"former_partner": "Ricci Rivero"},
    },
    "belle_mariano": {
        "full_name": "Belle Mariano",
        "birthdate": "June 10, 2002",
        "birthplace": "Pasig City, Philippines",
        "nationality": "Filipino",
        "occupation": "actress, singer",
        "known_for": "He's Into Her; DonBelle love team",
        "parents": {"father": "Michael Mariano", "mother": "Katrina Mariano"},
        "relationships": {"partner": "Donny Pangilinan"},
    },
    "donny_pangilinan": {
        "full_name": "Donny Pangilinan",
        "birthdate": "February 10, 1998",
        "birthplace": "Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "actor, singer",
        "known_for": "He's Into Her; son of Maricel Laxa",
        "parents": {"father": "Anthony Pangilinan", "mother": "Maricel Laxa"},
        "relationships": {"partner": "Belle Mariano"},
    },
    "heart_evangelista": {
        "full_name": "Heart Evangelista",
        "birthdate": "February 14, 1985",
        "birthplace": "Makati, Philippines",
        "nationality": "Filipino",
        "occupation": "actress, fashion icon",
        "known_for": "Paris Fashion Week regular; I Left My Heart in Sorsogon",
        "parents": {"father": "Reynaldo Ongpauco", "mother": "Cecilia Payawal"},
        "relationships": {"spouse": "Chiz Escudero"},
    },
    "solenn_heussaff": {
        "full_name": "Solenn Heussaff",
        "birthdate": "July 20, 1985",
        "birthplace": "Makati, Philippines",
        "nationality": "Filipino-French",
        "occupation": "actress, painter",
        "known_for": "Survivor Philippines; visual art exhibits; sister of Erwan",
        "parents": {"father": "Paul Heussaff", "mother": "Cynthia Adea"},
        "relationships": {"spouse": "Nico Bolzico", "children": "Thylane", "siblings": "Erwan Heussaff"},
    },
    "niana_guerrero": {
        "full_name": "Niana Guerrero",
        "birthdate": "January 27, 2006",
        "birthplace": "Quezon City, Philippines",
        "nationality": "Filipino",
        "occupation": "dancer, content creator",
        "known_for": "Viral TikTok dances with brother Ranz Kyle",
        "parents": {"father": "Niño Guerrero", "mother": "Elcid Guerrero"},
        "relationships": {"siblings": "Ranz Kyle"},
    },
    "ranz_kyle": {
        "full_name": "Ranz Kyle Viniel E. Ongsee",
        "birthdate": "May 6, 1997",
        "birthplace": "San Juan City, Philippines",
        "nationality": "Filipino",
        "occupation": "dancer, YouTuber",
        "known_for": "Ranz and Niana channel; Chicser dance group",
        "parents": {"father": "Niño Guerrero", "mother": "Elcid Guerrero"},
        "relationships": {"siblings": "Niana Guerrero"},
    },
    "cong_tv": {
        "full_name": "Lincoln Velasquez",
        "birthdate": "October 27, 1991",
        "birthplace": "Marikina, Philippines",
        "nationality": "Filipino",
        "occupation": "YouTuber, rapper, comedian",
        "known_for": "Team Payaman; one of the top Filipino YouTubers",
        "parents": {"father": "Nelson Velasquez", "mother": "Marites Velasquez"},
        "relationships": {"spouse": "Viy Cortez", "children": "Kidlat"},
    },
    "viy_cortez": {
        "full_name": "Viy Cortez",
        "birthdate": "July 23, 1996",
        "birthplace": "Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "YouTuber, businesswoman",
        "known_for": "Team Payaman vlogs; VIYLine cosmetics",
        "parents": {"father": "Alfredo Cortez", "mother": "Mila Cortez"},
        "relationships": {"spouse": "Cong TV", "children": "Kidlat"},
    },
    "alex_gonzaga": {
        "full_name": "Alex Gonzaga",
        "birthdate": "January 16, 1988",
        "birthplace": "Taytay, Rizal, Philippines",
        "nationality": "Filipino",
        "occupation": "actress, YouTuber, TV host",
        "known_for": "Comedy vlogs; younger sister of Toni Gonzaga",
        "parents": {"father": "Carlito Gonzaga", "mother": "Crisanta Cruz"},
        "relationships": {"spouse": "Mikee Morada", "siblings": "Toni Gonzaga"},
    },
    "ivana_alawi": {
        "full_name": "Ivana Alawi",
        "birthdate": "December 25, 1996",
        "birthplace": "Manila, Philippines",
        "nationality": "Filipino-Moroccan",
        "occupation": "actress, YouTuber",
        "known_for": "One of the most-subscribed Filipino YouTube channels",
        "parents": {"father": "Samier Al-Alawi", "mother": "Fatima Marbella"},
        "relationships": {"status": "single", "siblings": "Mona, Hash, Amira"},
    },
    "zeinab_harake": {
        "full_name": "Zeinab Harake",
        "birthdate": "December 11, 1998",
        "birthplace": "Manila, Philippines",
        "nationality": "Filipino-Lebanese",
        "occupation": "YouTuber, influencer",
        "known_for": "Family vlogs; Zebbiana fanbase",
        "parents": {"father": "Ali Harake", "mother": "Mariafe Ocampo"},
        "relationships": {"former_partner": "Skusta Clee", "children": "Bia"},
    },
    "wil_dasovich": {
        "full_name": "Wil Dasovich",
        "birthdate": "August 26, 1991",
        "birthplace": "Novato, California, USA",
        "nationality": "Filipino-American",
        "occupation": "travel vlogger, YouTuber",
        "known_for": "Travel vlogs across the Philippines; Pinoy Big Brother housemate",
        "parents": {"father": "Steve Dasovich", "mother": "Charry Dasovich"},
        "relationships": {"former_partner": "Alodia Gosiengfiao"},
    },
    "alodia_gosiengfiao": {
        "full_name": "Alodia Gosiengfiao",
        "birthdate": "March 9, 1988",
        "birthplace": "Quezon City, Philippines",
        "nationality": "Filipino",
        "occupation": "cosplayer, streamer, entrepreneur",
        "known_for": "Queen of Philippine cosplay; Tier One Entertainment co-founder",
        "parents": {"father": "Ed Gosiengfiao", "mother": "Mariglor Arraiza"},
        "relationships": {"spouse": "Christopher Quimbo", "former_partner": "Wil Dasovich"},
    },
    "regine_velasquez": {
        "full_name": "Regine Velasquez-Alcasid",
        "birthdate": "April 22, 1970",
        "birthplace": "Tondo, Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "singer, actress",
        "known_for": "Asia's Songbird; highest-selling Filipina recording artist",
        "parents": {"father": "Gerardo Velasquez", "mother": "Teresita Velasquez"},
        "relationships": {"spouse": "Ogie Alcasid", "children": "Nate"},
    },
    "ogie_alcasid": {
        "full_name": "Ogie Alcasid",
        "birthdate": "August 27, 1967",
        "birthplace": "Manila, Philippines",
        "nationality": "Filipino",
        "occupation": "singer-songwriter, comedian",
        "known_for": "Bubble Gang cast; prolific OPM songwriter",
        "parents": {"father": "Herminio Alcasid", "mother": "Soledad Alcasid"},
        "relationships": {"spouse": "Regine Velasquez", "children": "Nate"},
    },
    "bamboo_manalac": {
        "full_name": "Bamboo Mañalac",
        "birthdate": "March 21, 1976",
        "birthplace": "San Francisco, California, USA",
        "nationality": "Filipino-American",
        "occupation": "singer, TV judge",
        "known_for": "Rivermaya frontman; The Voice of the Philippines coach",
        "parents": {"father": "Renato Mañalac", "mother": "Teresa Mañalac"},
        "relationships": {"spouse": "Cecil Mañalac"},
    },
    "moira_dela_torre": {
        "full_name": "Moira Dela Torre",
        "birthdate": "November 4, 1993",
        "birthplace": "Olongapo City, Philippines",
        "nationality": "Filipino",
        "occupation": "singer-songwriter",
        "known_for": "Tagpuan and Malaya — top-streamed Filipino ballads",
        "parents": {"father": "Jesse Dela Torre", "mother": "Mariche Dela Torre"},
        "relationships": {"former_spouse": "Jason Hernandez"},
    },
    "kz_tandingan": {
        "full_name": "KZ Tandingan",
        "birthdate": "March 11, 1992",
        "birthplace": "Digos, Davao del Sur, Philippines",
        "nationality": "Filipino",
        "occupation": "singer",
        "known_for": "X Factor Philippines winner; Singer 2018 in China",
        "parents": {"father": "Jose Tandingan", "mother": "Bernadette Tandingan"},
        "relationships": {"spouse": "TJ Monterde"},
    },
    "morissette_amon": {
        "full_name": "Morissette Amon",
        "birthdate": "June 2, 1996",
        "birthplace": "Cebu City, Philippines",
        "nationality": "Filipino",
        "occupation": "singer",
        "known_for": "Asia's Phoenix; 'Akin Ka Na Lang' whistle notes",
        "parents": {"father": "Amay Amon", "mother": "Analie Amon"},
        "relationships": {"spouse": "Dave Lamar"},
    },
    "catriona_gray": {
        "full_name": "Catriona Gray",
        "birthdate": "January 6, 1994",
        "birthplace": "Cairns, Queensland, Australia",
        "nationality": "Filipino-Australian",
        "occupation": "beauty queen, model, TV host",
        "known_for": "Miss Universe 2018; lava walk",
        "parents": {"father": "Ian Gray", "mother": "Normita Ragas"},
        "relationships": {"former_partner": "Sam Milby"},
    },
    "pia_wurtzbach": {
        "full_name": "Pia Wurtzbach",
        "birthdate": "September 24, 1989",
        "birthplace": "Stuttgart, Germany",
        "nationality": "Filipino-German",
        "occupation": "beauty queen, actress",
        "known_for": "Miss Universe 2015 — ended the Philippines' 42-year drought",
        "parents": {"father": "Uwe Wurtzbach", "mother": "Cheryl Alonzo"},
        "relationships": {"spouse": "Jeremy Jauncey"},
    },
}
